---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
  - name: Get kubectl version
    ansible.builtin.command: "/usr/local/bin/kubectl version --client"
    failed_when: false
    changed_when: false
    register: kubectl_version_installed

  - name: Ensure kubectl is correct version
    ansible.builtin.assert:
      that: '"1.21.1" in kubectl_version_installed.stdout'

  - name: Get helm version
    ansible.builtin.command: "/usr/local/bin/helm version"
    failed_when: false
    changed_when: false
    register: helm_version

  - name: Ensure helm is correct version
    ansible.builtin.assert:
      that: '"3.7.1" in helm_version.stdout'

  - name: Get istioctl version
    ansible.builtin.command: "/usr/local/bin/istioctl version"
    failed_when: false
    changed_when: false
    register: istioctl_version

  - name: Ensure istioctl is correct version
    ansible.builtin.assert:
      that: '"1.14.1" in istioctl_version.stdout'

  - name: Get azwi version
    ansible.builtin.command: "/usr/local/bin/azwi version"
    failed_when: false
    changed_when: false
    register: azwi_version

  - name: Ensure azwi is correct version
    ansible.builtin.assert:
      that: '"0.10.0" in azwi_version.stdout'
