---
- name: Download Argo kubectl plugin
  ansible.builtin.get_url:
    # As of 11/30/2021 the only arch is amd64 for releases
    url: "{{ kubetools_argo_dl_url }}"
    dest: /usr/local/bin/kubectl-argo-rollouts
    mode: u=rwx,g=rx,o=rx
    owner: "{{ kubetools_user_id }}"
    group: "{{ kubetools_group_id }}"

### User rc files
- name: Configure user rc files for Argo
  ansible.builtin.lineinfile:
    path: "~{{ kubetools_user_id }}/{{ item.value }}"
    line: "source <(kubectl argo rollouts completion {{ item.key }})"
    create: true
    mode: u=rw,g=r,o=r
    owner: "{{ kubetools_user_id }}"
    group: "{{ kubetools_group_id }}"
  with_dict:
    bash: .bashrc
    zsh: .zshrc.local
