---
- name: Verify Argo binary
  stat:
    path: "{{ kubetools_argo_bin_path }}"
  register: argo_binary

- name: Verify Argo version
  command: "{{ kubetools_argo_bin_path }} version"
  failed_when: false
  changed_when: false
  register: argo_version

- name: Download Argo kubectl plugin
  ansible.builtin.get_url:
    # As of 11/30/2021 the only arch is amd64 for releases
    url: "{{ kubetools_argo_dl_url }}"
    dest: "{{ kubetools_argo_bin_path }}"
    mode: u=rwx,g=rwx,o=rx
    owner: "{{ kubetools_user_id }}"
    group: "{{ kubetools_group_id }}"
  when: not argo_binary.stat.exists or kubetools_argo_version not in argo_version.stdout

### User rc files
- name: Configure user rc files for Argo
  ansible.builtin.lineinfile:
    path: "~{{ kubetools_user_id }}/{{ item.value }}"
    line: "source <(kubectl argo rollouts completion {{ item.key }}) {{ kubetools_managed_by }}"
    create: true
    mode: u=rw,g=r,o=r
    owner: "{{ kubetools_user_id }}"
    group: "{{ kubetools_group_id }}"
  with_dict:
    bash: .bashrc
    zsh: .zshrc.local
