---
- name: Verify kubectl binary
  ansible.builtin.stat:
    path: "{{ kubetools_kubectl_bin_path }}"
  register: kubectl_binary

- name: Verify kubectl version
  ansible.builtin.command: "{{ kubetools_kubectl_bin_path }} version --client"
  failed_when: false
  changed_when: false
  register: kubectl_version

- name: "Download kubectl binary ({{ ansible_system | lower }} {{ kubetools_arch[ansible_architecture] }})"
  become: True
  ansible.builtin.get_url:
    url: "{{ kubetools_kubectl_dl_url }}"
    dest: "{{ kubetools_bin_path }}"
    mode: u=rwx,g=rx,o=rx
    owner: "{{ kubetools_user_id }}"
    group: "{{ kubetools_group_id }}"
  when: not kubectl_binary.stat.exists or kubetools_kubectl_version not in kubectl_version.stdout

# kube config
- name: Ensure kube config folder exists
  ansible.builtin.file:
    state: directory
    path: "{{ kubetools_config_source_dir }}"
    mode: u=rwx,g=rx
    owner: "{{ kubetools_user_id }}"
    group: "{{ kubetools_group_id }}"

- name: Write kube config files
  ansible.builtin.copy:
    dest: "{{ kubetools_config_source_dir }}/{{ item.key }}"
    content: "{{ item.value }}"
    mode: u=rw
    owner: "{{ kubetools_user_id }}"
    group: "{{ kubetools_group_id }}"
  with_dict: "{{ kubetools_kube_conf_files }}"
  no_log: true
  when: kubetools_kube_conf_files is defined

### User rc files
- name: Configure dot files for kubectl
  ansible.builtin.blockinfile:
    path: "~{{ kubetools_user_id }}/{{ item }}"
    create: true
    mode: u=rw,g=r,o=r
    owner: "{{ kubetools_user_id }}"
    group: "{{ kubetools_group_id }}"
    marker: "# {mark} ------------------ {{ kubetools_managed_by }}"
    block: |
      alias k=kubectl
      export do="-o=yaml --dry-run=client"
  loop:
    - ".bash_profile"
    - ".zshenv"

- name: Configure bash autocomplete for kubectl
  ansible.builtin.lineinfile:
    path: "~{{ kubetools_user_id }}/.bashrc"
    line: "{{ item }} {{ kubetools_managed_by }}"
    create: true
    mode: u=rw,g=r,o=r
    owner: "{{ kubetools_user_id }}"
    group: "{{ kubetools_group_id }}"
  loop:
    - 'source <(kubectl completion bash)'
    - 'complete -F __start_kubectl k'

- name: Configure zshell autocomplete for kubectl
  ansible.builtin.lineinfile:
    path: "~{{ kubetools_user_id }}/.zshrc.local"
    line: "{{ item }} {{ kubetools_managed_by }}"
    create: true
    mode: u=rw,g=r,o=r
    owner: "{{ kubetools_user_id }}"
    group: "{{ kubetools_group_id }}"
  loop:
    - '[[ $commands[kubectl] ]] && source <(kubectl completion zsh)'
  when: kubetools_shell_type == 'zsh'
