---
# - name: Extract kustomize
#   ansible.builtin.unarchive:
#     remote_src: yes
#     src: "{{ kubetools_kustomize_dl_url }}"
#     dest: "{{ kubetools_bin_path }}"
#     extra_opts: [--strip-components=1]
#     mode: u=rwx,g=rx,o=rx
#     owner: "{{ kubetools_user_id }}"
#     group: "{{ kubetools_group_id }}"

- name: Verify Kustomize binary
  ansible.builtin.stat:
    path: "{{ kubetools_kustomize_bin_path }}"
  register: kustomize_binary

- name: Verify Kustomize version
  ansible.builtin.command: "{{ kubetools_kustomize_bin_path }} version"
  failed_when: false
  changed_when: false
  register: kustomize_version

- name: Download kustomize archive
  ansible.builtin.get_url:
    url: "{{ kubetools_kustomize_dl_url }}"
    dest: /tmp/kustomize.tar.gz
    mode: u=rw,g=rw,o=r
    owner: "{{ kubetools_user_id }}"
    group: "{{ kubetools_group_id }}"
  register: kustomize_downloaded
  when: not kustomize_binary.stat.exists or kubetools_kustomize_version not in kustomize_version.stdout

- name: Extract kustomize
  ansible.builtin.unarchive:
    remote_src: yes
    src: /tmp/kustomize.tar.gz
    dest: "{{ kubetools_bin_path }}"
    extra_opts: [--strip-components=1]
    mode: u=rwx,g=rx,o=rx
    owner: "{{ kubetools_user_id }}"
    group: "{{ kubetools_group_id }}"
  when: ansible_system == 'Linux' and kustomize_downloaded is changed

# Because gnu-tar isn't found in path on remote Mac systems in non-interactive shell, use cmd to extract instead
- name: Extract kustomize with shell
  ansible.builtin.shell: |
    gtar -xvf /tmp/kustomize.tar.gz -C {{ kubetools_bin_path }}
    chown {{ kubetools_user_id }}:{{ kubetools_group_id }} {{ kubetools_bin_path }}
    # mode: u=rwx,g=rx,o=rx
  when: ansible_system == 'Darwin' and kustomize_downloaded is changed
  changed_when: False
