---
- name: Extract kustomize
  ansible.builtin.unarchive:
    remote_src: yes
    src: "{{ kustomize_dl_url }}"
    dest: "{{ kctl_bin_path }}"
    extra_opts: [--strip-components=1]
    mode: u=rwx,g=rx,o=rx
    owner: "{{ kctl_user_id }}"
    group: "{{ kctl_group_id }}"
