---
# installs
- name: Install kubectl
  include_tasks: kubectl.yml

- name: Install helm
  include_tasks: helm.yml
  when: kubetools_helm_version is defined

- name: Install kustomize
  include_tasks: kustomize.yml
  when: kubetools_kustomize_version is defined

- name: Install Tanzu CLI
  include_tasks: tanzu.yml
  when: kubetools_tanzu_install == true

- name: Install Argo stuff
  include_tasks: argo.yml
  when: kubetools_argo_version is defined

- name: Configure vimrc for kube usage
  ansible.builtin.lineinfile:
    path: "~{{ kubetools_user_id }}/.vimrc"
    line: "{{ item }} {{ kubetools_managed_by }}"
    create: true
    mode: u=rw,g=r,o=r
    owner: "{{ kubetools_user_id }}"
    group: "{{ kubetools_group_id }}"
  loop:
    - 'set expandtab'
    - 'set tabstop=2'
    - 'set shiftwidth=2'
