---
- name: Download kubectl binary (Linux amd64)
  become: yes
  ansible.builtin.get_url:
    url: "{{ kubectl_dl_url }}"
    dest: /usr/local/bin/
    mode: u=rwx,g=rx,o=rx
    owner: root
    group: "{{ kctl_admin_group_by_os[ansible_system] }}"

- name: Install helm
  include: helm.yml

- name: Install kustomize
  include: kustomize.yml

### User rc files
- name: Configure .bashrc for k8s
  ansible.builtin.lineinfile:
    path: "{{ kctl_user_home_path_by_os[ansible_system] }}/.bashrc"
    line: "{{ item }}"
    create: true
    mode: u=rw,g=r,o=r
    owner: "{{ kctl_user_id }}"
    group: "{{ kctl_user_id }}"
  loop:
    - 'source <(kubectl completion bash)'
    - 'alias k=kubectl'
    - 'complete -F __start_kubectl k'
    - 'export do="-o yaml --dry-run=client"'

- name: Configure kubectl completion for zshell
  ansible.builtin.lineinfile:
    path: "{{ kctl_user_home_path_by_os[ansible_system] }}/.zshrc.local"
    line: "{{ item }}"
    create: true
    mode: u=rw,g=r,o=r
    owner: "{{ kctl_user_id }}"
    group: "{{ kctl_user_id }}"
  loop:
    - 'alias k=kubectl'
    - '[[ $commands[kubectl] ]] && source <(kubectl completion zsh)'
    - 'export do="-o yaml --dry-run=client"'
  when: kctl_shell_type == 'zsh'

- name: Configure vimrc for kube usage
  ansible.builtin.lineinfile:
    path: "{{ kctl_user_home_path_by_os[ansible_system] }}/.vimrc"
    line: "{{ item }}"
    create: true
    mode: u=rw,g=r,o=r
    owner: "{{ kctl_user_id }}"
    group: "{{ kctl_user_id }}"
  loop:
    - 'set expandtab'
    - 'set tabstop=2'
    - 'set shiftwidth=2'
