---
- name: Download kubectl binary (Linux amd64)
  ansible.builtin.get_url:
    url: "{{ kubectl_dl_url }}"
    dest: "{{ kctl_bin_path }}"
    mode: u=rwx,g=rx,o=rx
    owner: "{{ kctl_user_id }}"
    group: "{{ kctl_group_id }}"

- name: Install helm
  include: helm.yml

- name: Install kustomize
  include: kustomize.yml

### User rc files
- name: Configure .bashrc for k8s
  ansible.builtin.lineinfile:
    path: "~{{ kctl_user_id }}/.bashrc"
    line: "{{ item }}"
    create: true
    mode: u=rw,g=r,o=r
    owner: "{{ kctl_user_id }}"
    group: "{{ kctl_group_id }}"
  loop:
    - 'source <(kubectl completion bash)'
    - 'alias k=kubectl'
    - 'complete -F __start_kubectl k'
    - 'export do="--dry-run=client --save-config -o yaml"'

- name: Configure kubectl completion for zshell
  ansible.builtin.lineinfile:
    path: "~{{ kctl_user_id }}/.zshrc.local"
    line: "{{ item }}"
    create: true
    mode: u=rw,g=r,o=r
    owner: "{{ kctl_user_id }}"
    group: "{{ kctl_group_id }}"
  loop:
    - 'alias k=kubectl'
    - '[[ $commands[kubectl] ]] && source <(kubectl completion zsh)'
    - 'export do="--dry-run=client --save-config -o yaml"'
  when: kctl_shell_type == 'zsh'

- name: Configure vimrc for kube usage
  ansible.builtin.lineinfile:
    path: "~{{ kctl_user_id }}/.vimrc"
    line: "{{ item }}"
    create: true
    mode: u=rw,g=r,o=r
    owner: "{{ kctl_user_id }}"
    group: "{{ kctl_group_id }}"
  loop:
    - 'set expandtab'
    - 'set tabstop=2'
    - 'set shiftwidth=2'
