---
- name: Download kubectl binary (Linux amd64)
  ansible.builtin.get_url:
    url: "{{ kubectl_dl_url }}"
    dest: "{{ kctl_bin_path }}"
    mode: u=rwx,g=rx,o=rx
    owner: "{{ kctl_user_id }}"
    group: "{{ kctl_group_id }}"

- name: Install helm
  include_tasks: helm.yml

- name: Install kustomize
  include_tasks: kustomize.yml

### User rc files
- name: Configure .bashrc for kubectl
  ansible.builtin.lineinfile:
    path: "~{{ kctl_user_id }}/.bashrc"
    line: "{{ item }}"
    regexp: "^{{ item.split('=')[0] }}="
    create: true
    mode: u=rw,g=r,o=r
    owner: "{{ kctl_user_id }}"
    group: "{{ kctl_group_id }}"
  loop:
    - 'alias k=kubectl'
    - 'export do="-o yaml --dry-run=client"'

- name: Configure .zshrc.local for kubectl
  ansible.builtin.lineinfile:
    path: "~{{ kctl_user_id }}/.zshrc.local"
    line: "{{ item }}"
    regexp: "^{{ item.split('=')[0] }}="
    create: true
    mode: u=rw,g=r,o=r
    owner: "{{ kctl_user_id }}"
    group: "{{ kctl_group_id }}"
  loop:
    - 'alias k=kubectl'
    - 'export o="-o yaml"'
    - 'export d="--dry-run=client"'

- name: Configure bash autocomplete for kubectl
  ansible.builtin.lineinfile:
    path: "~{{ kctl_user_id }}/.bashrc"
    line: "{{ item }}"
    create: true
    mode: u=rw,g=r,o=r
    owner: "{{ kctl_user_id }}"
    group: "{{ kctl_group_id }}"
  loop:
    - 'source <(kubectl completion bash)'
    - 'complete -F __start_kubectl k'

- name: Configure zshell autocomplete for kubectl
  ansible.builtin.lineinfile:
    path: "~{{ kctl_user_id }}/.zshrc.local"
    line: "{{ item }}"
    create: true
    mode: u=rw,g=r,o=r
    owner: "{{ kctl_user_id }}"
    group: "{{ kctl_group_id }}"
  loop:
    - '[[ $commands[kubectl] ]] && source <(kubectl completion zsh)'
  when: kctl_shell_type == 'zsh'

- name: Configure vimrc for kube usage
  ansible.builtin.lineinfile:
    path: "~{{ kctl_user_id }}/.vimrc"
    line: "{{ item }}"
    create: true
    mode: u=rw,g=r,o=r
    owner: "{{ kctl_user_id }}"
    group: "{{ kctl_group_id }}"
  loop:
    - 'set expandtab'
    - 'set tabstop=2'
    - 'set shiftwidth=2'
