---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
  - name: Verify kubectl version
    ansible.builtin.command: "/home/chris/.local/bin/kubectl version --client"
    failed_when: false
    changed_when: false
    register: kubectl_version_installed

  - name: Ensure kubectl is correct version
    ansible.builtin.assert:
      that: '"1.24.10" in kubectl_version_installed.stdout'

  - name: Get helm version
    ansible.builtin.command: "/home/chris/.local/bin/helm version"
    failed_when: false
    changed_when: false
    register: helm_version

  - name: Ensure helm is correct version
    ansible.builtin.assert:
      that: '"3.11.1" in helm_version.stdout'
