name: Ansible Release
on:
  workflow_run:
    workflows:
      - 'Ansible Test'
    branches:
      - main
    types:
      - completed

jobs:
  job1:
    uses: Diehlabs/shared-workflows/.github/workflows/ansible-ci.yml@v0.0.1
