name: Ansible CI

on: [push, pull_request]

jobs:
  default:
    uses: Diehlabs/shared-workflows/.github/workflows/ansible-ci.yml@v0.0.2

  all_vars:
    uses: Diehlabs/shared-workflows/.github/workflows/ansible-ci.yml@v0.0.2
    with:
      scenario: all_vars
