name: Ansible Test

on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Lint Ansible Role
        uses: ansible/ansible-lint-action@master
        with:
          targets:
            tests/test.yml
          override-deps: |
            ansible==2.9
            ansible-lint==5.3.2

# name: Ansible Test
# on: [push, pull_request]
# jobs:
#   test:
#     uses: Diehlabs/.github/.github/workflows/ansible-test.yml@v.0.0.8
